### PR TITLE
Add possibility to use msgpack >= 0.5.0.

### PR DESCRIPTION
**Pull request by frodsan**
Right now we can't use ohm and disc together. More information: https://github.com/soveran/ohm/pull/195

### CODE REVIEW

**Comment by pote** [comment]
I spent some time testing different msgpack versions with Disc, unfortunately the oldest msgpack that works with it is `0.5.6`, do you know if it's possible to use that with Ohm?

**Comment by pote** [comment]
Update: just pushed an updated gemspec that has a range of msgpack versions known to work [in this branch](https://github.com/pote/disc/tree/frodsan-msgpack), I can merge that in and make a new release it if that sounds good.

**Comment by frodsan** [comment]
I'm using 0.5.12. I think that should work. Thanks!

**Comment by pote** [comment]
Just released `v0.0.23` including these changes. :)

**Comment by frodsan** [comment]
Awesome :+1:

**Pull request merged**
